const mongoose = require('mongoose');

const PartnerSchema = new mongoose.Schema({
  hotelOwnerName: String,
  ownerContactDetails: String,
  receptionContactDetails: String,
  hotelEmail: String,
  generalManagerContact: String,
  salesManagerContact: String,
  hotelDetails: String,
  street: String,
  city: String,
  state: String,
  zip: String,
  landmark: String,
  starType: String,
  propertyType: String,
  images: [String],
  amenities:[String],
  // amenities: {
  //   "Free Wireless Internet": Boolean,
  //   "Air Conditioning": Boolean,
  //   "Room Services": Boolean,
  //   "Clean And Disinfect": Boolean,
  //   "School Diatacing": Boolean,
  //   "Free Parking": Boolean,
  //   "House Keeping": Boolean,
  //   "Towels": Boolean,
  //   "Complimentary Tolietries": Boolean,
  //   "Good Showers": Boolean,
  //   "Cable Tv": Boolean,
  //   "Bottled Water": Boolean,
  //   "Swimming Pool": Boolean,
  //   "On-site Restaurant": Boolean,
  //   "Hair Dryer": Boolean,
  //   "Fitness Center": Boolean,
  //   "Conclerge Desk": Boolean,
  //   "Spa": Boolean,
  //   "Dry Cleaning": Boolean,
  //   "Bathrobe": Boolean,
  //   "24 Hour Front Desk Service": Boolean, 
  // },
    "outsideFoodPolicy":String,
      "cancellationPolicy":String,
      "paymentMode":String,
      "petsAllowed":String,
      "bachelorAllowed":String,
      "smokingAllowed":String,
      "alcoholAllowed":String,
      "unmarriedCouplesAllowed":String,
      "internationalGuestAllowed":String,
      "returnPolicy":String,
      "checkInOut":String,
    "onDoubleSharing" : String,
    "onQuadSharing" : String,
    "onBulkBooking" : String,
    "onTrippleSharing" : String,
    "onMoreThanFour" : String,
    "offDoubleSharing" : String,
    "offQuadSharing" : String,
    "offBulkBooking" : String,
    "offTrippleSharing" : String,
    "offMoreThanFour" : String,
    "onDoubleSharingAp" : String,
    "onQuadSharingAp" : String,
    "onBulkBookingAp" : String,
    "onTrippleSharingAp" : String,
    "onMoreThanFourAp" : String,
    "offDoubleSharingAp" : String,
    "offQuadSharingAp" : String,
    "offBulkBookingAp" : String,
    "offTrippleSharingAp" : String,
    "offMoreThanFourAp" : String,
    "onDoubleSharingMAp" : String,
    "onQuadSharingMAp" : String,
    "onBulkBookingMAp" : String,
    "onTrippleSharingMAp" : String,
    "onMoreThanFourMAp" : String,
    "offDoubleSharingMAp" : String,
    "offQuadSharingMAp" : String,
    "offBulkBookingMAp" : String,
    "offTrippleSharingMAp" : String,
    "offMoreThanFourMAp" : String
});


module.exports =mongoose.model('Partner', PartnerSchema);
